# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows_2019_VS2019_x64
  displayName: "Windows 2019, VS 2019, x64"
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -G "Visual Studio 16 2019" -A x64 ..
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'RelWithDebInfo'
- job: Windows_2016_VS2017_x64
  displayName: "Windows 2016, VS 2017, x64"
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -G "Visual Studio 15 2017 Win64" ..
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'RelWithDebInfo'
- job: Windows_2012R2_VS2015_x64
  displayName: "Windows 2012 R2, VS 2015, x64"
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: -G "Visual Studio 14 2015 Win64" ..
  - task: MSBuild@1
    inputs:
      solution: 'build/*.sln'
      msbuildArchitecture: 'x64'
      platform: 'x64'
      configuration: 'RelWithDebInfo'
- job: Ubuntu_1804_GCC
  displayName: "Ubuntu 18.04"
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo apt install -y libsodium-dev
    displayName: Install libsodium-dev
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  - script: |
      cd build && make
    displayName: Make
- job: Ubuntu_1604_GCC
  displayName: "Ubuntu 16.04"
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt install -y libsodium-dev
    displayName: Install libsodium-dev
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  - script: |
      cd build && make
    displayName: Make
- job: macOS_1014
  displayName: "macOS 10.14"
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      brew install libsodium
    displayName: Install libsodium
  - task: CMake@1
    inputs:
      cmakeArgs: -G ..
  - script: |
      cd build && make
    displayName: Make
- job: macOS_1013
  displayName: "macOS 10.13"
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      brew install libsodium
    displayName: Install libsodium
  - task: CMake@1
    inputs:
      cmakeArgs: -G ..
  - script: |
      cd build && make
    displayName: Make