# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

jobs:
- job: Windows_2019_VS2019
  pool:
    vmImage: 'windows-2019'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ..
- job: Windows_2016_VS2017
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ..
- job: Windows_2012R2_VS2015
  pool:
    vmImage: 'vs2015-win2012r2'
  steps:
  - task: CMake@1
    inputs:
      cmakeArgs: ..
- job: Ubuntu_1804_GCC
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - script: |
      sudo apt install -y libsodium-dev
    displayName: Install libsodium-dev
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  - script: |
      cd build && make
    displayName: Make
- job: Ubuntu_1604_GCC
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: |
      sudo apt install -y libsodium-dev
    displayName: Install libsodium-dev
  - task: CMake@1
    inputs:
      cmakeArgs: ..
  - script: |
      cd build && make
    displayName: Make
- job: macOS_1014
  pool:
    vmImage: 'macOS-10.14'
  steps:
  - script: |
      sudo brew install libsodium
    displayName: Install libsodium
  - task: CMake@1
    inputs:
      cmakeArgs: ..
- job: macOS_1013
  pool:
    vmImage: 'macOS-10.13'
  steps:
  - script: |
      sudo brew install libsodium
    displayName: Install libsodium
  - task: CMake@1
    inputs:
      cmakeArgs: ..